FROM ubuntu
RUN apt-get update && apt-get -y  upgrade && apt-get autoremove && apt-get install -y net-tools  && apt-get install -y  git software-properties-common curl
RUN apt update && \
    apt install -y -q software-properties-common nano mysql-client iputils-ping
RUN add-apt-repository ppa:ondrej/php
ENV DEBIAN_FRONTEND=noninteractive
RUN DEBIAN_FRONTEND=noninteractive apt  install -y tzdata

#RUN apt-get update && \
 #   apt-get install -y -q php8.0-cli php8.0-fpm php8.0-gd php8.0-curl php8.0-mysql php8.0-mbstring php8.0-xml php8.0-zip php8.0-bcmath php8.0-soap php8.0-mongodb


ENV NODE_VERSION 16.0.0
RUN apt update\
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash\
    && . $HOME/.nvm/nvm.sh\
    && nvm install $NODE_VERSION\
    && nvm use $NODE_VERSION
ENV NODE_PATH /root/.nvm/v$NODE_VERSION/lib/node_modules
ENV PATH /root/.nvm/versions/node/v$NODE_VERSION/bin:$PATH
#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN apt-get -y update && apt -y install nginx
RUN apt-get update && \
    apt-get install -y -q php8.0-cli php8.0-fpm php8.0-gd php8.0-curl php8.0-mysql php8.0-mbstring php8.0-xml php8.0-zip php8.0-bcmath php8.0-soap php8.0-mongodb
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --no-cache

ADD ssl-bundle.crt /etc/ssl/certs/
ADD myhive-control.com.key  /etc/ssl/private/myhive-control.com.key
COPY hive.conf  /etc/nginx/sites-available/hive.conf
RUN ln -s /etc/nginx/sites-available/hive.conf /etc/nginx/sites-enabled/
RUN unlink /etc/nginx/sites-enabled/default && nginx -t
WORKDIR /var/www/html
RUN apt-get update
ARG username 
ARG password
WORKDIR /var/www/html
ARG CACHEBUST=1
RUN cd /var/www/html && git clone --single-branch --branch development  https://${username}:${password}@github.com/EmbedTech-Solutions-Pvt-Ltd/DCC-CMS && chown -R $USER:www-data DCC-CMS 



COPY .env.example /var/www/html/DCC-CMS/.env.example





# INSTALLING SUPERVISOR
RUN apt-get update && apt-get install -y supervisor
COPY websockets.conf  /etc/supervisor/conf.d/websockets.conf
COPY queues.conf /etc/supervisor/conf.d/queues.conf
COPY short_schedule.conf /etc/supervisor/conf.d/short_schedule.conf

# INSTALIING PHP MY ADMIN
RUN apt-get install wget unzip
RUN cd  /usr/share &&  wget https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.zip -O phpmyadmin.zip && unzip phpmyadmin.zip && rm phpmyadmin.zip && mv phpMyAdmin-*-all-languages phpmyadmin && chmod -R 0755 phpmyadmin && ln -s /usr/share/phpmyadmin/ /var/www/html/DCC-CMS/public/phpmyadmin && mkdir /usr/share/phpmyadmin/tmp/
RUN chown -R www-data:www-data /usr/share/phpmyadmin/tmp/
#EXPOSE 80



#Install Cron
RUN apt-get update
RUN apt-get -y install cron
ADD cron_setup.sh /var/www/html/DCC-CMS/
RUN chmod 777 /var/www/html/DCC-CMS/cron_setup.sh
RUN crontab -l | { cat; echo "* * * * * /var/www/html/DCC-CMS/cron_setup.sh >> /var/log/cron.log 2>&1"; } | crontab -

ADD hive-init.sh /var/www/html/
ADD seed.sh /var/www/html
ADD update.sh /var/www/html

#ENTRYPOINT sh hive-init.sh
RUN cd /var/www/html/DCC-CMS && composer install 
#COPY hive-init.sh /var/www/html/DCC-CMS/hive-init.sh
RUN cd /var/www/html/DCC-CMS && cp .env.example .env  
RUN cd /var/www/html/DCC-CMS && npm install   && npm run prod
RUN cd /var/www/html/DCC-CMS && chown -R $USER:$USER vendor/   && chmod -R 777 storage && chown -R www-data:www-data storage

CMD sh hive-init.sh  && tail -f /dev/null  
EXPOSE 6001

